language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements.txt
  - pip install isort black flake8 pylint
  - pip install codecov
script:
  - python tests.py
  - coverage run tests.py
  - isort --check-only --recursive coderunner
  - black --check --diff coderunner
  - flake8 coderunner --max-line-length=88 --ignore=F401
  - pylint coderunner --disable=bad-continuation,invalid-name,too-many-instance-attributes,too-many-arguments,attribute-defined-outside-init,no-self-use
after_success:
  - codecov
