site_name: CodeRunner
site_url: https://codeclassroom.github.io/CodeRunner/
repo_url: https://github.com/codeclassroom/CodeRunner
site_author: Bhupesh Varshney
site_description: CodeRunner v1.0 Documentation
copyright: © 2020, Bhupesh Varshney
nav:
    - Documentation: index.md
    - Installation: installation.md
    - Usage: usage.md
    - Judge0: judge0.md
    - Changelog: changelog.md
    - About: about.md
theme: readthedocs
markdown_extensions:
    - toc:
        permalink: "#"