site_name: CodeRunner
repo_url: https://github.com/codeclassroom/CodeRunner
site_author: Bhupesh Varshney
site_description: CodeRunner v0.3 Documentation
copyright: © 2019, Bhupesh Varshney
nav:
    - Home: index.md
    - Installation: installation.md
    - Usage: usage.md
    - About: about.md
theme: readthedocs
markdown_extensions:
    - toc:
        permalink: "#"